services:
  news_quickly:
    image: ghcr.io/zhaocore/news_quickly:latest
    container_name: news_quickly
    ports:
      - '4444:4444'
    volumes:
      - news_quickly_data:/usr/app/.data
    environment:
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true
      - PRODUCTHUNT_API_TOKEN=

volumes:
  news_quickly_data:
    name: news_quickly_data
